style: format code with Prettier

diff --git a/.github/workflows/prettier.yml b/.github/workflows/prettier.yml
--- a/.github/workflows/prettier.yml
+++ b/.github/workflows/prettier.yml
@@ -15,14 +15,16 @@ jobs:
           cmd: install
       - name: Prettier Check 🔎
         id: prettier
-        run: npx prettier . --check
+        run: | 
+          npx prettier . --check || echo "needs_formatting=true" >> $GITHUB_OUTPUT
+          exit 0  # Prevent the step from failing the pipeline
       - name: Run Prettier 🦋
         # https://docs.github.com/en/actions/learn-github-actions/expressions#failure
-        if: ${{ failure() }}
+        if: ${{  steps.prettier.outputs.needs_formatting == 'true' }}
         run: |
           npx prettier . --write
       - name: Commit and push changes ⬆️
-        if: ${{ failure() && steps.prettier.conclusion == 'failure' }}
+        if: ${{  steps.prettier.outputs.needs_formatting == 'true' }}
         run: |
           git config user.name "Jaume Barber"
           git config user.email "jbarber@hipervincle.com"
